// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLinkCommandButton: typeof import('./src/components/MenuCommands/AddLinkCommandButton.vue')['default']
    CommandButton: typeof import('./src/components/MenuCommands/CommandButton.vue')['default']
    Counter: typeof import('./playground/components/Counter.vue')['default']
    CreateTablePopover: typeof import('./src/components/MenuCommands/table/CreateTablePopover.vue')['default']
    EditImageCommadButton: typeof import('./src/components/MenuCommands/image/EditImageCommadButton.vue')['default']
    FontColorPopover: typeof import('./src/components/MenuCommands/FontColorPopover.vue')['default']
    Footer: typeof import('./playground/components/Footer.vue')['default']
    GuoduIcon: typeof import('./src/components/GuoduIcon.vue')['default']
    HeadingCommandButton: typeof import('./src/components/MenuCommands/HeadingCommandButton.vue')['default']
    HighlightPopover: typeof import('./src/components/MenuCommands/HighlightPopover.vue')['default']
    ImageDisplayCommandButton: typeof import('./src/components/MenuCommands/image/ImageDisplayCommandButton.vue')['default']
    ImageView: typeof import('./src/components/ExtensionViews/ImageView.vue')['default']
    InsertImageCommandButton: typeof import('./src/components/MenuCommands/InsertImageCommandButton.vue')['default']
    LinkBubbleMenu: typeof import('./src/components/MenuBubble/LinkBubbleMenu.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/index.vue')['default']
    MenuBubble: typeof import('./src/components/MenuBubble/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBubbleMenu: typeof import('./src/components/MenuBubble/TableBubbleMenu.vue')['default']
    TablePopover: typeof import('./src/components/MenuCommands/TablePopover.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap.vue')['default']
  }
}
