[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "npx pnpm i --no-frozen-lockfile && npx pnpm run build:demo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
