export { default as Text } from '@tiptap/extension-text'
export { default as Document } from './document'
export { default as Paragraph } from '@tiptap/extension-paragraph'
// extensions
export { default as History } from './history'
export { default as Gapcursor } from './gapcursor'
export { default as Dropcursor } from './dropcursor'
export { default as Focus } from './focus'
export { default as Placeholder } from './placeholder'
export { default as FormatClear } from './format-clear'
export { default as TextAlign } from './text-align'
export { default as Color } from './color'
export { default as Fullscreen } from './fullscreen'
export { default as CustomCommands } from './commands'
export { default as ImportWord } from './import-word'
export { default as Indent } from './indent'

// marks
export { default as Bold } from './marks/bold'
export { default as Code } from './marks/code'
export { default as Emphasis } from './marks/emphasis'
export { default as Italic } from './marks/italic'
export { default as Strike } from './marks/strike'
export { default as Subscript } from './marks/subscript'
export { default as Superscript } from './marks/superscript'
export { default as Underline } from './marks/underline'
export { default as Link } from './marks/link'
export { default as Highlight } from './marks/highlight'
export { default as FontFamily } from './marks/font-family'
export { default as LineHeight } from './marks/line-height'
// Nodes
export { default as Heading } from './nodes/heading'
export { default as BulletList } from './nodes/bullet-list'
export { default as OrderedList } from './nodes/ordered-list'
export { default as TaskList } from './nodes/task-list'
export { default as Blockquote } from './nodes/blockquote'
export { default as HorizontalRule } from './nodes/horizontal-rule'
export { default as Image } from './nodes/image'
export { default as Table } from './nodes/table'
export { default as CodeBlockLowlight } from './nodes/code-block-lowlight'
export { default as Math } from './nodes/math'

